### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by xuzheng0017** [ch3nnn/webstack-go#60]
启动后第一次跳转到/install界面，安装好初始化后重启服务一直跳转到这个/install界面。麻烦帮忙看下。
日志告警：
```shell
{"level":"error","time":"2023-09-08 17:47:49","caller":"core/core.go:377","msg":"got panic","domain":"go-gin-api[docker]","panic":"runtime error: invalid memory address or nil pointer dereference","stack":"goroutine 38 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/ch3nnn/webstack-go/internal/pkg/core.New.func2.1()\n\t/var/jenkins_home/workspace/public-webstack-online/internal/pkg/core/core.go:376 +0x14c\npanic({0x11a29a0, 0x3b22cc0})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\ngithub.com/ch3nnn/webstack-go/internal/services/category.(*service).Tree(0x134aa52?, {0x206f498?, 0xc00029a040?})\n\t/var/jenkins_home/workspace/public-webstack-online/internal/services/category/service_tree.go:33 +0xa4\ngithub.com/ch3nnn/webstack-go/internal/api/index.(*handler).Index.func1({0x206f498, 0xc00029a040})\n\t/var/jenkins_home/workspace/public-webstack-online/internal/api/index/func_index.go:25 +0xa5\ngithub.com/ch3nnn/webstack-go/internal/pkg/core.wrapHandlers.func1(0xc000242200)\n\t/var/jenkins_home/workspace/public-webstack-online/internal/pkg/core/core.go:214 +0xbe\ngithub.com/gin-gonic/gin.(*Context).Next(...)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/ch3nnn/webstack-go/internal/pkg/core.New.func3(0xc000242200)\n\t/var/jenkins_home/workspace/public-webstack-online/internal/pkg/core/core.go:547 +0x268\ngithub.com/gin-gonic/gin.(*Context).Next(...)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/ch3nnn/webstack-go/internal/pkg/core.New.func2(0xc000242200)\n\t/var/jenkins_home/workspace/public-webstack-online/internal/pkg/core/core.go:529 +0x29f\ngithub.com/gin-gonic/gin.(*Context).Next(...)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/ch3nnn/webstack-go/internal/pkg/core.New.func1(0xc000242200)\n\t/var/jenkins_home/workspace/public-webstack-online/internal/pkg/core/core.go:333 +0x6d\ngithub.com/gin-gonic/gin.(*Context).Next(...)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000581d40, 0xc000242200)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x671\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000581d40, {0x2062210?, 0xc0003082a0}, 0xc000242100)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd\ngithub.com/ch3nnn/webstack-go/internal/pkg/core.(*mux).ServeHTTP(0x0?, {0x2062210?, 0xc0003082a0?}, 0xc000071800?)\n\t/var/jenkins_home/workspace/public-webstack-online/internal/pkg/core/core.go:234 +0x26\nnet/http.serverHandler.ServeHTTP({0xc0002c0120?}, {0x2062210, 0xc0003082a0}, 0xc000242100)\n\t/usr/local/go/src/net/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc000124280, {0x2063160, 0xc0003b1530})\n\t/usr/local/go/src/net/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3071 +0x4db\n"}
```

**Comment by ch3nnn** [comment]
我刚刚用最新的代码并没有出现你这边错误。  运行方式 docker-compose。

**Comment by xuzheng0017** [comment]
我的问题，最新的代码我没关注docker-compose文件，没挂载lock文件。感谢！
